post:
    path:     /
    defaults: { _controller: "WojtekOrderBundle:Post:index" }

post_show:
    path:     /{id}/show
    defaults: { _controller: "WojtekOrderBundle:Post:show" }

post_new:
    path:     /new
    defaults: { _controller: "WojtekOrderBundle:Post:new" }

post_new_from_file:
    path:     /new-from-file
    defaults: { _controller: "WojtekOrderBundle:Post:newFromFile" }

post_add_from_file:
    path:     /add-from-file
    defaults: { _controller: "WojtekOrderBundle:Post:addFromFile" }

post_create:
    path:     /create
    defaults: { _controller: "WojtekOrderBundle:Post:create" }
    methods:  POST

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "WojtekOrderBundle:Post:edit" }

post_update:
    path:     /{id}/update
    defaults: { _controller: "WojtekOrderBundle:Post:update" }
    methods:  [POST, PUT]

post_delete:
    path:     /{id}/delete
    defaults: { _controller: "WojtekOrderBundle:Post:delete" }
    methods:  [POST, DELETE]

post_update_payment_status:
    path:     /{id}/update-payment-status
    defaults: { _controller: "WojtekOrderBundle:Post:updatePaymentStatus" }
